#+title: Dotfiles para Archlinux con Qtile como window manager

** Instalación de Archlinux

*Agregue la instalación de Archlinux por si a alguien le llega interesar, ya que no hay mucha información en español que describa paso a paso la instalación limpia de Archlinux de manera manual*

[[documents/install-arch.org]]

** Configuración de Archlinux (Dotfiles)

*** Gestor de ventanas

El gestor de ventanas que uso es Qtile, Qtile es un gestor de ventanas para el escritorio de Linux que está escrito en Python, es completamente programable y configurable, lo que significa que puedes ajustar su comportamiento y apariencia exactamente a tus necesidades.
Antes de instalar Qtile es necesario instalar Python, ya que sin el no es posible usar Qtile, para esta instalación y configuración no es necesario conocer este lenguaje de programación, pero si deseas personalizar a tu gusto Qtile, es recomendable saber por lo menos cosas basicas de Python.

*Aqui te dejo los paquetes nesesarios para instalar Qtile*

- Python

#+begin_src sh
sudo pacman -S python
#+end_src

- Qtile y Qtile-extras
Para instalar Qtile es nesesario instalar estos dos paquetes, el paquete *qtile* es el manejador de ventanas basico, pero si quieres que tenga mas herramientas de personalización es necesario instalar *qtile-extras* <br>
*Si deseas instalar mas de dos paquetes al mismo tiempo, puedes colocarlos en la misma linea de comandos usando un espacio como separador*

#+begin_src sh
sudo pacman -S qtile qtile-extras
#+end_src

Con esto ya podrias reiniciar tu PC e iniciar sesión con Qtile como tu manejador de ventanas, pero esta es una instalación basica de qtile, por lo que los atajos de teclado de Qtile son los que tiene por default y es posible que no los conozcas, para eso es necesario configurar Qtile segun nuestras necesidades.

*Yo uso una configuración de Qtile que no es mia, es de otra persona que ha creado esta configuración y ha decidido compartirla para que mas personas la puedan usar, esta configuración es de mis favoritas y es la que vamos a instalar.*

El creador de esta configuración de Qtile es jx11r, aqui les dejo el repositorio de su configuración:

[[https://github.com/jx11r/qtile]]

Pero antes de usar de esta configuración es necesario instalar los paquetes que se utilizan en esta configuración, ya que sin estos no funciona la configuración de jx11r.

1. Paquetes necesarios
    - *otf-hasklig-nerd*: fuente (Font)
    - *pacman-contrib*: scripts y herramientas contribuidos para pacman
    - *pamixer*: controla los niveles de volumen
    - *python-dbus-next*: es una biblioteca de Python para DBus que pretende ser una biblioteca de alto nivel con todas las funciones y orientada principalmente a la integración de aplicaciones en entornos móviles y de escritorio de Linux.
    - *python-psutil*: es una biblioteca multiplataforma para recuperar información sobre procesos en ejecución y utilización del sistema
    - *ttf-nerd-fonts-symbols-mono:* fuente (Font)

#+begin_src sh
sudo pacman -S otf-hasklig-nerd pacman-contrib pamixer python-dbus-next python-psutil ttf-nerd-fonts-symbols-mono
#+end_src

2. Paquetes opcionales
    - *playerctl*: es una utilidad de línea de comandos y una biblioteca para controlar reproductores multimedia
    - *brightnessctl*: Este programa le permite leer y controlar el brillo del dispositivo

#+begin_src sh
sudo pacman -S playerctl brightnessctl
#+end_src

3. Ahora si podemos clonar el repositorio de jx11r y agregarlo a nuestra carpeta de configuración

#+begin_src sh
git clone https://github.com/jx11r/qtile.git ~/.config/qtile
#+end_src

*Con esta configuración ya deberias de poder usar Qtile como manejador de ventanas, si quieres saber mas hacerca de la configuración o como moverte con este manejador, te dejo un pequeño manual para que puedas configurar y saber usar Qtile*

[[documents/qtile.org]]

*** Herramientas

Ahora instalaremos algunas herramientas que nos facilitaran el trabajo en este sistema operativo.

- Kitty o Alacritty

Por default Archlinux trae instalaco xterm como terminal, puedes usar esa terminal que esta por default o instalar Kitty o Alacritty, esto es decición tuya, yo solo te dejare las dos y tu decides cual instalar. Puedes instalar ambas, no hay ningun problema.

1. *Kitty*: es un emulador de terminal basado en GPU, rápido y rico en funciones.

#+begin_src sh
sudo pacman -S kitty
#+end_src

2. *Alacritty*: es un emulador de terminal moderno que viene con valores predeterminados sensibles, pero permite una configuración extensa, al parecer aun esta en fase beta, pero se puede usar sin problemas.

#+begin_src sh
sudo pacman -S alacritty
#+end_src

- Fish o Bash

Por default Archlinux trae instalado Bash como shell, pero la puedes cambiar segun tus necesidades o gustos, esto depende de ti. Aqui te dejo la configuración de Bash y Fish para que decidas con cual quieres trabajar, esto no quiere decir que no puedas usar las dos al mismo tiempo, pero es recomendable que solo uses una.

*\* La shell es es un programa que proporciona una interfaz de usuario para acceder a los servicios del sistema operativo. Funciona como una capa intermedia entre el usuario y el núcleo del sistema operativo, permitiendo al usuario interactuar con el sistema mediante la ejecución de comandos.*

1. Bash: es una interfaz de usuario de línea de comandos popular, específicamente un shell de Unix; así como un lenguaje de scripting.
Como mensione anteriormente, Bash ya esta instalada por default en Archlinux y es la que estas usando en este momento, asi que no es necesario instalarla, pero si no esta seguro de que shell estas usando, puedes ejecutar el siguiente comando:

#+begin_src sh
echo $SHELL
#+end_src

Ahora puedes personalizar bash segun tus necesidades, aqui te dejo algunas herramientas que te facilitan el uso de bash, puedes elegir cual instalar o usar:
    -  Oh My Bash: [[https://github.com/ohmybash/oh-my-bash]]
    Oh My Bash es un framework para gestionar la configuración y personalización de la línea de comandos Bash. Con puedes instalar plugins para agilizar el trabajo de la shell asi como instalar temas para la Powerline.

    Para instalar Oh My Bash, puedes seguir la guia que esta en el repo, pero te dejo aqui el metodo de insalación. Si llegas a presentar algun problema con este comando, es mejor ver la documentacion oficial.
    
    #+begin_src sh
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
    #+end_src

    Al instalar Oh My Bash podras ver en tu home el archivo .bashrc, si ejecutas el comando `cat ~/.bashrc` podras ver el contenido del archivo y ver las configuraciones que trae por default, para editar el archivo e instalar algunos plugins puedes usar nano.

    a. Plugins

    #+begin_src sh
    nano .bashrc
    #+end_src

    Para moverte dentro de nano puedes usar las teclas dirección (flechas). En la parte de plugins veras que ya hay dos plugins preinstalados:

    #+begin_src sh
    plugins=(
        git
        bashmarks
    )
    #+end_src

    Si deceas ver que plugins para bash estan disponibles, te dejo esta URL donde se listan en carpetas todos los plugins disponibles: [[https://github.com/ohmybash/oh-my-bash/tree/master/plugins]]

    Ahora instalaremos el plugin sudo, este plugin te ayuda a completar algun comando que quieras ejecutar con sudo, por ejemplo, si escribes `pacman -S git` pero se te olvido escribir la palabra sudo al principio, entonces este plugin te permite acompletar esto presionando dos veces la tecla Esc. Entonces la parte de plugins deberia de quedar asi: 

    plugins=(
        git
        bashmarks
        sudo
    )
    
    Ahora para instalar este plugin guardamos el archivo con Ctrl + o, confirmamos el guardado y salimos del editor con Ctrl + x. y reiniciamos la configuración con source ~/.bashrc. Con esto ya deberia de estar instalado el plugin sudo, ahora solo faltaria probarlo.

    b. Temas: para los temas personalmente a mi no me gustan los que trae Oh My Bash, pero si deceas instalar alguno, lo puedes revisar en el repositorio que te deje anteriormente. Si no instalas algun tema puedes ver como aplicamos un tema para la Powerline mas abajo.

2. Fish: fish es un shell de línea de comandos inteligente y fácil de usar para Linux, macOS y el resto de la familia.

