#+title: Dotfiles para Archlinux con Qtile como window manager

* Instalación de Archlinux

*Agregue la instalación de Archlinux por si a alguien le llega interesar, ya que no hay mucha información en español que describa paso a paso la instalación limpia de Archlinux de manera manual*

[[documents/install-arch.org]]

** Primeros pasos

Despues de la instalación basica de Archlinux, deberiamos de validar la conexión a internet, si no estas conectado por cable es necesario conectarte por Wifi.

#+begin_src sh
nmcli device wifi list
nmcli device wifi connect NOMBRE_DE_WIFI password CONTRASEÑA
#+end_src

Ahora para instalar entornos de escritorio es necesario instalar xorg.

#+begin_src sh
sudo pacman -S xorg
#+end_src

Ahora es necesario instalar paquetes que nos ayudaran descargar archivos y repositorios desde la terminal

#+begin_src sh
sudo pacman -S git curl wget firefox
#+end_src

* Configuración de Archlinux

** Inicio de sesión

#+begin_src sh
sudo pacman -S lightdm lightdm-gtk-greeter
sudo systemctl enable lightdm
#+end_src

** Gestor de ventanas

El gestor de ventanas que uso es Qtile, Qtile es un gestor de ventanas para el escritorio de Linux que está escrito en Python, es completamente programable y configurable, lo que significa que puedes ajustar su comportamiento y apariencia exactamente a tus necesidades.
Antes de instalar Qtile es necesario instalar Python, ya que sin el no es posible usar Qtile, para esta instalación y configuración no es necesario conocer este lenguaje de programación, pero si deseas personalizar a tu gusto Qtile, es recomendable saber por lo menos cosas basicas de Python.

*Aqui te dejo los paquetes nesesarios para instalar Qtile*

- Python

#+begin_src sh
sudo pacman -S python
#+end_src

- Qtile y Qtile-extras
Para instalar Qtile es nesesario instalar estos dos paquetes, el paquete *qtile* es el manejador de ventanas basico, pero si quieres que tenga mas herramientas de personalización es necesario instalar *qtile-extras* <br>
*Si deseas instalar mas de dos paquetes al mismo tiempo, puedes colocarlos en la misma linea de comandos usando un espacio como separador*

#+begin_src sh
sudo pacman -S qtile qtile-extras
#+end_src

Con esto ya podrias reiniciar tu PC e iniciar sesión con Qtile como tu manejador de ventanas, pero esta es una instalación basica de qtile, por lo que los atajos de teclado de Qtile son los que tiene por default y es posible que no los conozcas, para eso es necesario configurar Qtile segun nuestras necesidades.

*Yo uso una configuración de Qtile que no es mia, es de otra persona que ha creado esta configuración y ha decidido compartirla para que mas personas la puedan usar, esta configuración es de mis favoritas y es la que vamos a instalar.*

El creador de esta configuración de Qtile es jx11r, aqui les dejo el repositorio de su configuración:

[[https://github.com/jx11r/qtile]]

Pero antes de usar de esta configuración es necesario instalar los paquetes que se utilizan en esta configuración, ya que sin estos no funciona la configuración de jx11r.

- Paquetes necesarios
    - *otf-hasklig-nerd*: fuente (Font)
    - *pacman-contrib*: scripts y herramientas contribuidos para pacman
    - *pamixer*: controla los niveles de volumen
    - *python-dbus-next*: es una biblioteca de Python para DBus que pretende ser una biblioteca de alto nivel con todas las funciones y orientada principalmente a la integración de aplicaciones en entornos móviles y de escritorio de Linux.
    - *python-psutil*: es una biblioteca multiplataforma para recuperar información sobre procesos en ejecución y utilización del sistema
    - *ttf-nerd-fonts-symbols-mono:* fuente (Font)

#+begin_src sh
sudo pacman -S otf-hasklig-nerd pacman-contrib pamixer python-dbus-next python-psutil ttf-nerd-fonts-symbols-mono
#+end_src

- Paquetes opcionales
    - *playerctl*: es una utilidad de línea de comandos y una biblioteca para controlar reproductores multimedia
    - *brightnessctl*: Este programa le permite leer y controlar el brillo del dispositivo

#+begin_src sh
sudo pacman -S playerctl brightnessctl
#+end_src

- Ahora si podemos clonar el repositorio de jx11r y agregarlo a nuestra carpeta de configuración

#+begin_src sh
git clone https://github.com/jx11r/qtile.git ~/.config/qtile
#+end_src

Ahora solo reiniciamos el sistema y podremos iniciar sesión con Lightdm y Qtile

#+begin_src sh
reboot
#+end_src

*Con esta configuración ya deberias de poder usar Qtile como manejador de ventanas, si quieres saber mas hacerca de la configuración o como moverte con este manejador, te dejo un pequeño manual para que puedas configurar y saber usar Qtile*

[[documents/qtile.org]]

** Herramientas

Ahora instalaremos algunas herramientas que nos facilitaran el trabajo en este sistema operativo.

*** Rofi

Para buscar aplicaciones instaladas y poder ejecutarlas.

#+begin_src sh
sudo pacman -S rofi
#+end_src


*** Kitty o Alacritty

Por default Archlinux trae instalaco xterm como terminal, puedes usar esa terminal que esta por default o instalar Kitty o Alacritty, esto es decición tuya, yo solo te dejare las dos y tu decides cual instalar. Puedes instalar ambas, no hay ningun problema.

- *Kitty*: es un emulador de terminal basado en GPU, rápido y rico en funciones.

#+begin_src sh
sudo pacman -S kitty
#+end_src

- *Alacritty*: es un emulador de terminal moderno que viene con valores predeterminados sensibles, pero permite una configuración extensa, al parecer aun esta en fase beta, pero se puede usar sin problemas.

#+begin_src sh
sudo pacman -S alacritty
#+end_src

*** Fish o Bash

Por default Archlinux trae instalado Bash como shell, pero la puedes cambiar segun tus necesidades o gustos, esto depende de ti. Aqui te dejo la configuración de Bash y Fish para que decidas con cual quieres trabajar, esto no quiere decir que no puedas usar las dos al mismo tiempo, pero es recomendable que solo uses una.

*# La shell es es un programa que proporciona una interfaz de usuario para acceder a los servicios del sistema operativo. Funciona como una capa intermedia entre el usuario y el núcleo del sistema operativo, permitiendo al usuario interactuar con el sistema mediante la ejecución de comandos.*

**** Bash
- Bash: es una interfaz de usuario de línea de comandos popular, específicamente un shell de Unix; así como un lenguaje de scripting.
Como mensione anteriormente, Bash ya esta instalada por default en Archlinux y es la que estas usando en este momento, asi que no es necesario instalarla, pero si no esta seguro de que shell estas usando, puedes ejecutar el siguiente comando:

#+begin_src sh
echo $SHELL
#+end_src

Ahora puedes personalizar bash segun tus necesidades, aqui te dejo algunas herramientas que te facilitan el uso de bash, puedes elegir cual instalar o usar:
-  Oh My Bash: [[https://github.com/ohmybash/oh-my-bash]]
Oh My Bash es un framework para gestionar la configuración y personalización de la línea de comandos Bash. Con este framework puedes instalar plugins para agilizar el trabajo de la shell asi como instalar temas para la Powerline.

Para instalar Oh My Bash, puedes seguir la guia que esta en el repo, pero te dejo aqui el metodo de instalación. Si llegas a presentar algun problema con este comando, es mejor ver la documentacion oficial.

#+begin_src sh
bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
#+end_src

Al instalar Oh My Bash podras ver en tu home el archivo .bashrc, si ejecutas el comando =cat ~/.bashrc= podras ver el contenido del archivo y ver las configuraciones que trae por default, para editar el archivo e instalar algunos plugins puedes usar nano.

- Plugins

#+begin_src sh
nano .bashrc
#+end_src

Para moverte dentro de nano puedes usar las teclas dirección (flechas). En la parte de plugins veras que ya hay dos plugins preinstalados:

#+begin_src sh
plugins=(
    git
    bashmarks
)
#+end_src

Si deceas ver que plugins para bash estan disponibles, te dejo esta URL donde se listan en carpetas todos los plugins disponibles: [[https://github.com/ohmybash/oh-my-bash/tree/master/plugins]]

Ahora instalaremos el plugin sudo, este plugin te ayuda a completar algun comando que quieras ejecutar con sudo, por ejemplo, si escribes =pacman -S git= pero se te olvido escribir la palabra sudo al principio, entonces este plugin te permite acompletar esto presionando dos veces la tecla Esc. Entonces la parte de plugins deberia de quedar asi: 

#+begin_src sh
plugins=(
    git
    bashmarks
    sudo
)
#+end_src

Ahora para instalar este plugin guardamos el archivo con Ctrl + o, confirmamos el guardado y salimos del editor con Ctrl + x. y reiniciamos la configuración con el comando =source ~/.bashrc=. Con esto ya deberia de estar instalado el plugin sudo, ahora solo faltaria probarlo.

- Temas: para los temas personalmente a mi no me gustan los que trae Oh My Bash, pero si deceas instalar alguno, lo puedes revisar en el repositorio que te deje anteriormente. Si no instalas algun tema puedes ver como aplicamos un tema para la Powerline mas abajo.

**** fish

- Fish: fish es un shell de línea de comandos inteligente y fácil de usar para Linux, macOS y el resto de la familia.

#+begin_src sh
sudo pacman -S fish
#+end_src

Ahora para poder usar Fish en lugar de Bash ejecuta el comando =fish=.

Ya que esta instalado Fish lo puedes personalizar segun tus necesitades.

- Fisher: Fisher te permite instalar, actualizar y eliminar complementos. Disfrute de la finalización de pestañas de Fish y del rico resaltado de sintaxis mientras lo hace.
Para Fish instalaremos Fisher: [[https://github.com/jorgebucaran/fisher]]

Aqui te dejo el comando de instalación de Fisher, pero si tienes algun problema con este comando, visita el repositorio de Fisher.

#+begin_src sh
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
#+end_src

- Plugins
Aqui te dejo la lista de plugins disponibles con Fisher: [[https://github.com/jorgebucaran/awsm.fish?tab=readme-ov-file#plugins]]

Ahora instalaremos GitNow, este plugin nos ayuda a ejecutar comandos de alto nivel de git con atajos de teclado.
[[https://github.com/joseluisq/gitnow]]

#+begin_src sh
fisher install joseluisq/gitnow@2.12.0
#+end_src

Este es un ejemplo de instalacion de plugins, tu decides cual instalar.

- Temas
Para los temas de la Powerline pueden instalar el plugin tide =fisher install IlanCosman/tide@v5=. Al instalar este plugin te permitira configurar la apariencia de tu powerline, personalmente no me gusta ningun tema de la Powerline que trae tide. Si deceas ver que tema de la powerline yo uso lo explicare mas abajo en su respectivo espacio.

- Oh My Fish

Si deceas ver mas temas para la poweline de Fish, aqui te dejo otro paquete que te ayuda con eso, este paquete casi no lo he probado, asi que solo te dejo la URL

[[https://github.com/oh-my-fish/oh-my-fish]]

*Ahora como paso final es establecer Fish como la shell por default, esto en caso de que quieras usar Fish, si deceas usar Bash entonces omite este paso*

#+begin_src sh
chsh -s /usr/bin/fish
#+end_src

*** Lxarandr

Para modificar la resolución de tu pantalla o monitor existe la herramienta Lxarandr.

#+begin_src sh
sudo pacman -S lxarandr
#+end_src