font_size                       16

# Include
# include                         $HOME/.config/kitty/themes/tokyonight_moon.conf
include                         $HOME/.config/kitty/themes/Nord.conf
include                         $HOME/.config/kitty/tabs.conf
include                         $HOME/.config/kitty/mappings.conf

# Padding
window_padding_width            1

# Cursors
cursor_shape                    beam
cursor_beam_thickness           1

# Size
remember_window_size            yes
initial_window_width            640
initial_window_height           400

# Layouts
enabled_layouts                 horizontal,splits,grid,fat
window_resize_step_cells        1
window_resize_step_lines        1

# Border
window_border_width             1
hide_window_decorations         false
allow_remote_control            yes
titlebar_only                   true
titlebar_and_corners            true


# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font Mono"
bold_font        "SebBd"
italic_font      "Ret"
bold_italic_font "Bold"
# END_KITTY_FONTS
