palette = "catppuccin_mocha"
add_newline = false

# Editor completions
"$schema" = "https://starship.rs/config-schema.json"

# Prompt configuration
#format = """[󰣇](blue) [$localip](purple)[](purple)[](blue)$directory[](blue) $package\
format = """[󰣇](blue)[$localip](purple)$directory\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_branch\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[username]
format = '[$user](bg:purple fg:black bold)[$read_only]($read_only_style)'
disabled = false
show_always = true

[localip]
ssh_only = false
#format = '[ $localipv4 ](bg:purple fg:black bold)[$read_only]($read_only_style)'
format = '[ $localipv4 ](purple bold)'
disabled = false

[character]
success_symbol = '[❯](bold maroon) '
error_symbol = '[✗](bold red) '

[directory]
#format = '[ $path ](bg:blue fg:black bold)[$read_only]($read_only_style)'
format = '[ $path ](blue bold)'
truncation_length = 3
truncation_symbol = '…/'

# ~/.config/starship.toml

[package]
format = 'via [ $version](208 bold) '


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"