"$schema" = 'https://starship.rs/config-schema.json'

format = """
(surface0)\
$os\
$username\
[](fg:peach)\
$directory\
[](fg:green)\
$git_branch\
$git_status\
[](fg:teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:blue)\
$docker_context\
$line_break$character"""

palette = 'nord'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.nord]
polar_night_0 = "#2E3440"
polar_night_1 = "#3B4252"
polar_night_2 = "#434C5E"
polar_night_3 = "#4C566A"
snow_storm_0 = "#D8DEE9"
snow_storm_1 = "#E5E9F0"
snow_storm_2 = "#ECEFF4"
frost_blue = "#81A1C1"
frost_cyan = "#88C0D0"
aurora_red = "#BF616A"
aurora_orange = "#D08770"
aurora_yellow = "#EBCB8B"
aurora_green = "#A3BE8C"
aurora_purple = "#B48EAD"

[os]
disabled = false
style = "bold fg:snow_storm_0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰣇"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bold fg:snow_storm_0"
style_root = "bold fg:snow_storm_0"
format = '[ $user ]($style)'

[directory]
style = "bold dimmed fg:snow_storm_0"
# style = "bold fg:polar_night_1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:aurora_green)]($style)'

[git_status]
style = "bold"
format = '[[($all_status $ahead_behind )](fg:aurora_green)]($style)'

[nodejs]
symbol = ""
style = "fg:frost_cyan"
format = '[[ $symbol( $version) ](fg:frost_cyan)]($style)'

[c]
symbol = " "
style = "fg:frost_cyan"
format = '[[ $symbol( $version) ](fg:frost_cyan)]($style)'

[rust]
symbol = ""
style = "fg:frost_cyan"
format = '[[ $symbol( $version) ](fg:frost_cyan)]($style)'

[golang]
symbol = ""
style = "fg:frost_cyan"
format = '[[ $symbol( $version) ](fg:frost_cyan)]($style)'

[php]
symbol = ""
style = "fg:frost_cyan"
format = '[[ $symbol( $version) ](fg:frost_cyan)]($style)'

[java]
symbol = " "
style = "fg:frost_cyan"
format = '[[ $symbol( $version) ](fg:frost_cyan)]($style)'

[kotlin]
symbol = ""
style = "fg:frost_cyan"
format = '[[ $symbol( $version) ](fg:frost_cyan)]($style)'

[haskell]
symbol = ""
style = "fg:frost_cyan"
format = '[[ $symbol( $version) ](fg:frost_cyan)]($style)'

[python]
symbol = ""
style = "fg:frost_cyan"
format = '[[ $symbol( $version) ](fg:frost_cyan)]($style)'

[docker_context]
symbol = ""
style = "fg:polar_night_1"
format = '[[ $symbol( $context) ](fg:polar_night_2)]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:aurora_orange"
format = '[[  $time ](fg:aurora_purple)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:aurora_green)'
error_symbol = '[](bold fg:aurora_red)'
vimcmd_symbol = '[](bold fg:aurora_green)'
vimcmd_replace_one_symbol = '[](bold fg:aurora_purple)'
vimcmd_replace_symbol = '[](bold fg:aurora_purple)'
vimcmd_visual_symbol = '[](bold fg:frost_blue)'
