return {}
-- return {
--   {
--     "barreiroleo/ltex_extra.nvim",
--     ft = { "markdown", "tex", "text" },
--     dependencies = { "neovim/nvim-lspconfig" },
--     config = function()
--       local capabilities = require("cmp_nvim_lsp").default_capabilities()
--
--       -- Idiomas que usarás
--       local langs = { "en-US", "es" }
--
--       -- Ruta para los diccionarios
--       local dict_path = vim.fn.expand("~") .. "/.local/share/ltex"
--
--       -- Crear archivos de diccionario si no existen
--       for _, lang in ipairs(langs) do
--         local file = dict_path .. "/" .. lang .. ".txt"
--         if vim.fn.filereadable(file) == 0 then
--           vim.fn.mkdir(dict_path, "p")
--           io.open(file, "w"):close()
--         end
--       end
--
--       -- Configuración de ltex_extra
--       require("ltex_extra").setup({
--         load_langs = langs,
--         init_check = true,
--         path = dict_path,
--         log_level = "info",
--         server_opts = {
--           capabilities = capabilities,
--           on_attach = function(client, bufnr)
--             -- Aquí puedes mapear keymaps si lo deseas
--           end,
--           settings = {
--             ltex = {
--               language = "es", -- idioma base
--               additionalLanguages = { "en-US" }, -- idioma secundario
--               dictionary = {
--                 ["en-US"] = {},
--                 ["es"] = {},
--               },
--               disabledRules = {
--                 ["en-US"] = {},
--                 ["es"] = {},
--               },
--               hiddenFalsePositives = {
--                 ["en-US"] = {},
--                 ["es"] = {},
--               },
--             },
--           },
--         },
--       })
--
--       -- Comando global para cambiar el idioma del buffer actual
--       vim.api.nvim_create_user_command("SetLtexLang", function(opts)
--         local lang = opts.args
--         vim.lsp.buf_notify(0, "workspace/didChangeConfiguration", {
--           settings = {
--             ltex = {
--               language = lang,
--             },
--           },
--         })
--       end, {
--         nargs = 1,
--         complete = function()
--           return langs
--         end,
--       })
--     end,
--   },
-- }
