"$schema" = 'https://starship.rs/config-schema.json'

format = """
(surface0)\
$os\
$username\
[](fg:peach)\
$directory\
[](fg:green)\
$git_branch\
$git_status\
[](fg:teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:blue)\
$docker_context\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# OS Module
[os]
disabled = false
style = "fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

# Username Module
[username]
show_always = true
style_user = "fg:blue"
style_root = "fg:blue"
format = '[ $user ]($style)'

# Local IP Module
[localip]
ssh_only = false
style = "fg:surface0"
format = '[ $localipv4 ]($style)'
disabled = false

# Directory Module
[directory]
style = "fg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

# Git Branch Module
[git_branch]
symbol = ""
style = "fg:teal"
format = '[[ $symbol $branch ](fg:green)]($style)'

# Git Status Module
[git_status]
style = "fg:teal"
format = '[[($all_status$ahead_behind )](fg:green)]($style)'

# Node.js Module
[nodejs]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# C Module
[c]
symbol = " "
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Rust Module
[rust]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Go Module
[golang]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# PHP Module
[php]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Java Module
[java]
symbol = " "
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Kotlin Module
[kotlin]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Haskell Module
[haskell]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Python Module
[python]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Docker Context Module
[docker_context]
symbol = ""
style = "fg:mantle"
format = '[[ $symbol( $context) ](fg:color_bg3)]($style)'

# Time Module
[time]
disabled = false
time_format = "%R"
style = "fg:peach"
format = '[[  $time ](fg:purple)]($style)'

# Line Break Module
[line_break]
disabled = false

# Character Module
[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
