"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
$docker_context\
$line_break$character"""

palette = 'solarized_dark'

[palettes.solarized_dark]
rosewater = "#d33682"
flamingo = "#cb4b16"
pink = "#6c71c4"
orange = "#b58900"
red = "#dc322f"
maroon = "#859900"
peach = "#b58900"
yellow = "#b58900"
green = "#859900"
teal = "#2aa198"
sky = "#268bd2"
sapphire = "#073642"
blue = "#268bd2"
lavender = "#6c71c4"
text = "#fdf6e3"
subtext1 = "#eee8d5"
subtext0 = "#93a1a1"
overlay2 = "#839496"
overlay1 = "#657b83"
overlay0 = "#586e75"
surface2 = "#073642"
surface1 = "#002b36"
surface0 = "#001f27"
base = "#002b36"
mantle = "#001f27"
crust = "#000d11"

# OS Module
[os]
disabled = false
style = "fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

# Username Module
[username]
show_always = true
style_user = "fg:blue"
style_root = "fg:blue"
format = '[ $user ]($style)'

# Local IP Module
[localip]
ssh_only = false
style = "fg:surface0"
format = '[ $localipv4 ]($style)'
disabled = false

# Directory Module
[directory]
style = "fg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

# Git Branch Module
[git_branch]
symbol = ""
style = "fg:teal"
format = '[[ $symbol $branch ](fg:green)]($style)'

# Git Status Module
[git_status]
style = "fg:teal"
format = '[[($all_status$ahead_behind )](fg:green)]($style)'

# Node.js Module
[nodejs]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# C Module
[c]
symbol = " "
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Rust Module
[rust]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Go Module
[golang]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# PHP Module
[php]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Java Module
[java]
symbol = " "
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Kotlin Module
[kotlin]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Haskell Module
[haskell]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Python Module
[python]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Lua Module
[lua]
symbol = "󰢱"
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

# Docker Context Module
[docker_context]
symbol = ""
style = "fg:mantle"
format = '[[ $symbol( $context) ](fg:color_bg3)]($style)'

# Time Module
[time]
disabled = false
time_format = "%R"
style = "fg:peach"
format = '[[  $time ](fg:purple)]($style)'

# Line Break Module
[line_break]
disabled = false

# Character Module
[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
